### ISSUE TITLE
1.0: High-level blockers

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#662]
We are talking more and more about 1.0 blockers informally, and I want to have a central place to track them across both platforms.

* [x] `ViewRegistry` – should i stay or should i go? (#390)
* [ ] `mapOutput` in Swift vs `runningWorker` in Kotlin (#544, #583)
* [x] `WorkflowAction` boilerplate reduction (aka do we bring back `emitOutput`?) (#644)
* [ ] Data classes break binary backwards compatibility (#779)

**Comment by SalvatoreT** [comment]
> `WorkflowAction` boilerplate reduction (aka do we bring back `emitOutput`?)
I mostly use `WorkflowAction` as a lambda, so it looks like this everywhere.

```
sink.send(WorkflowAction {
  this.state = EnteringName(state.firstName, state.lastName)
  null
})
```

**Comment by zach-klippenstein** [comment]
@SalvatoreT Can you comment on #644 instead? This issue is for tracking the group of issues, not the actual issues themselves.

**Comment by JustinDSN** [comment]
Obsolete now that we have discrete tickets and milestones and labels oh my!
